// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: omnitun/v1/common.proto

package omnitunv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_omnitun_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_omnitun_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *PaginationResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_omnitun_v1_common_proto protoreflect.FileDescriptor

const file_omnitun_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x17omnitun/v1/common.proto\x12\n" +
	"omnitun.v1\"A\n" +
	"\x11PaginationRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"P\n" +
	"\x12PaginationResponse\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMoreB\x9d\x01\n" +
	"\x0ecom.omnitun.v1B\vCommonProtoP\x01Z5github.com/omnitun/omnitun/proto/omnitun/v1;omnitunv1\xa2\x02\x03OXX\xaa\x02\n" +
	"Omnitun.V1\xca\x02\n" +
	"Omnitun\\V1\xe2\x02\x16Omnitun\\V1\\GPBMetadata\xea\x02\vOmnitun::V1b\x06proto3"

var (
	file_omnitun_v1_common_proto_rawDescOnce sync.Once
	file_omnitun_v1_common_proto_rawDescData []byte
)

func file_omnitun_v1_common_proto_rawDescGZIP() []byte {
	file_omnitun_v1_common_proto_rawDescOnce.Do(func() {
		file_omnitun_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omnitun_v1_common_proto_rawDesc), len(file_omnitun_v1_common_proto_rawDesc)))
	})
	return file_omnitun_v1_common_proto_rawDescData
}

var file_omnitun_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_omnitun_v1_common_proto_goTypes = []any{
	(*PaginationRequest)(nil),  // 0: omnitun.v1.PaginationRequest
	(*PaginationResponse)(nil), // 1: omnitun.v1.PaginationResponse
}
var file_omnitun_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_omnitun_v1_common_proto_init() }
func file_omnitun_v1_common_proto_init() {
	if File_omnitun_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omnitun_v1_common_proto_rawDesc), len(file_omnitun_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_omnitun_v1_common_proto_goTypes,
		DependencyIndexes: file_omnitun_v1_common_proto_depIdxs,
		MessageInfos:      file_omnitun_v1_common_proto_msgTypes,
	}.Build()
	File_omnitun_v1_common_proto = out.File
	file_omnitun_v1_common_proto_goTypes = nil
	file_omnitun_v1_common_proto_depIdxs = nil
}
