// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: omnitun/v1/tunnel.proto

package omnitunv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tunnel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Slug           string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Protocol       string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	LocalPort      int32                  `protobuf:"varint,7,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	LocalHost      string                 `protobuf:"bytes,8,opt,name=local_host,json=localHost,proto3" json:"local_host,omitempty"`
	CustomDomain   string                 `protobuf:"bytes,9,opt,name=custom_domain,json=customDomain,proto3" json:"custom_domain,omitempty"`
	TlsMode        string                 `protobuf:"bytes,10,opt,name=tls_mode,json=tlsMode,proto3" json:"tls_mode,omitempty"`
	AuthMode       string                 `protobuf:"bytes,11,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	Status         string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	BytesInTotal   int64                  `protobuf:"varint,13,opt,name=bytes_in_total,json=bytesInTotal,proto3" json:"bytes_in_total,omitempty"`
	BytesOutTotal  int64                  `protobuf:"varint,14,opt,name=bytes_out_total,json=bytesOutTotal,proto3" json:"bytes_out_total,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Tunnel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tunnel) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Tunnel) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Tunnel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tunnel) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tunnel) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Tunnel) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *Tunnel) GetLocalHost() string {
	if x != nil {
		return x.LocalHost
	}
	return ""
}

func (x *Tunnel) GetCustomDomain() string {
	if x != nil {
		return x.CustomDomain
	}
	return ""
}

func (x *Tunnel) GetTlsMode() string {
	if x != nil {
		return x.TlsMode
	}
	return ""
}

func (x *Tunnel) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

func (x *Tunnel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tunnel) GetBytesInTotal() int64 {
	if x != nil {
		return x.BytesInTotal
	}
	return 0
}

func (x *Tunnel) GetBytesOutTotal() int64 {
	if x != nil {
		return x.BytesOutTotal
	}
	return 0
}

func (x *Tunnel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tunnel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	LocalPort     int32                  `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	LocalHost     string                 `protobuf:"bytes,5,opt,name=local_host,json=localHost,proto3" json:"local_host,omitempty"`
	CustomDomain  string                 `protobuf:"bytes,6,opt,name=custom_domain,json=customDomain,proto3" json:"custom_domain,omitempty"`
	TlsMode       string                 `protobuf:"bytes,7,opt,name=tls_mode,json=tlsMode,proto3" json:"tls_mode,omitempty"`
	AuthMode      string                 `protobuf:"bytes,8,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTunnelRequest) Reset() {
	*x = CreateTunnelRequest{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTunnelRequest) ProtoMessage() {}

func (x *CreateTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTunnelRequest.ProtoReflect.Descriptor instead.
func (*CreateTunnelRequest) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTunnelRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTunnelRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateTunnelRequest) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *CreateTunnelRequest) GetLocalHost() string {
	if x != nil {
		return x.LocalHost
	}
	return ""
}

func (x *CreateTunnelRequest) GetCustomDomain() string {
	if x != nil {
		return x.CustomDomain
	}
	return ""
}

func (x *CreateTunnelRequest) GetTlsMode() string {
	if x != nil {
		return x.TlsMode
	}
	return ""
}

func (x *CreateTunnelRequest) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

type CreateTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTunnelResponse) Reset() {
	*x = CreateTunnelResponse{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTunnelResponse) ProtoMessage() {}

func (x *CreateTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTunnelResponse.ProtoReflect.Descriptor instead.
func (*CreateTunnelResponse) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type GetTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelRequest) Reset() {
	*x = GetTunnelRequest{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelRequest) ProtoMessage() {}

func (x *GetTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelRequest.ProtoReflect.Descriptor instead.
func (*GetTunnelRequest) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *GetTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type GetTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelResponse) Reset() {
	*x = GetTunnelResponse{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelResponse) ProtoMessage() {}

func (x *GetTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelResponse.ProtoReflect.Descriptor instead.
func (*GetTunnelResponse) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *GetTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *ListTunnelsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListTunnelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTunnelsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListTunnelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*Tunnel              `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *ListTunnelsResponse) GetTunnels() []*Tunnel {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

func (x *ListTunnelsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateTunnelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TunnelId       string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Name           *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	AuthMode       *string                `protobuf:"bytes,3,opt,name=auth_mode,json=authMode,proto3,oneof" json:"auth_mode,omitempty"`
	MaxConnections *int32                 `protobuf:"varint,4,opt,name=max_connections,json=maxConnections,proto3,oneof" json:"max_connections,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTunnelRequest) Reset() {
	*x = UpdateTunnelRequest{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTunnelRequest) ProtoMessage() {}

func (x *UpdateTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTunnelRequest.ProtoReflect.Descriptor instead.
func (*UpdateTunnelRequest) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *UpdateTunnelRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTunnelRequest) GetAuthMode() string {
	if x != nil && x.AuthMode != nil {
		return *x.AuthMode
	}
	return ""
}

func (x *UpdateTunnelRequest) GetMaxConnections() int32 {
	if x != nil && x.MaxConnections != nil {
		return *x.MaxConnections
	}
	return 0
}

type UpdateTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTunnelResponse) Reset() {
	*x = UpdateTunnelResponse{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTunnelResponse) ProtoMessage() {}

func (x *UpdateTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTunnelResponse.ProtoReflect.Descriptor instead.
func (*UpdateTunnelResponse) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type DeleteTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTunnelRequest) Reset() {
	*x = DeleteTunnelRequest{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTunnelRequest) ProtoMessage() {}

func (x *DeleteTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTunnelRequest.ProtoReflect.Descriptor instead.
func (*DeleteTunnelRequest) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type DeleteTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTunnelResponse) Reset() {
	*x = DeleteTunnelResponse{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTunnelResponse) ProtoMessage() {}

func (x *DeleteTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTunnelResponse.ProtoReflect.Descriptor instead.
func (*DeleteTunnelResponse) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTunnelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTunnelRequest) Reset() {
	*x = StartTunnelRequest{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelRequest) ProtoMessage() {}

func (x *StartTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelRequest.ProtoReflect.Descriptor instead.
func (*StartTunnelRequest) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{11}
}

func (x *StartTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type StartTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RelayAddress  string                 `protobuf:"bytes,2,opt,name=relay_address,json=relayAddress,proto3" json:"relay_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTunnelResponse) Reset() {
	*x = StartTunnelResponse{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelResponse) ProtoMessage() {}

func (x *StartTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTunnelResponse) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{12}
}

func (x *StartTunnelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartTunnelResponse) GetRelayAddress() string {
	if x != nil {
		return x.RelayAddress
	}
	return ""
}

type StopTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelRequest) Reset() {
	*x = StopTunnelRequest{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelRequest) ProtoMessage() {}

func (x *StopTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelRequest.ProtoReflect.Descriptor instead.
func (*StopTunnelRequest) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{13}
}

func (x *StopTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type StopTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTunnelResponse) Reset() {
	*x = StopTunnelResponse{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTunnelResponse) ProtoMessage() {}

func (x *StopTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTunnelResponse.ProtoReflect.Descriptor instead.
func (*StopTunnelResponse) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{14}
}

func (x *StopTunnelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTunnelStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelStatsRequest) Reset() {
	*x = GetTunnelStatsRequest{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelStatsRequest) ProtoMessage() {}

func (x *GetTunnelStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelStatsRequest.ProtoReflect.Descriptor instead.
func (*GetTunnelStatsRequest) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{15}
}

func (x *GetTunnelStatsRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *GetTunnelStatsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type TunnelStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BytesIn           int64                  `protobuf:"varint,1,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut          int64                  `protobuf:"varint,2,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	TotalRequests     int32                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TunnelStats) Reset() {
	*x = TunnelStats{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStats) ProtoMessage() {}

func (x *TunnelStats) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStats.ProtoReflect.Descriptor instead.
func (*TunnelStats) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{16}
}

func (x *TunnelStats) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *TunnelStats) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *TunnelStats) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *TunnelStats) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

type GetTunnelStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *TunnelStats           `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelStatsResponse) Reset() {
	*x = GetTunnelStatsResponse{}
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelStatsResponse) ProtoMessage() {}

func (x *GetTunnelStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnitun_v1_tunnel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelStatsResponse.ProtoReflect.Descriptor instead.
func (*GetTunnelStatsResponse) Descriptor() ([]byte, []int) {
	return file_omnitun_v1_tunnel_proto_rawDescGZIP(), []int{17}
}

func (x *GetTunnelStatsResponse) GetStats() *TunnelStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_omnitun_v1_tunnel_proto protoreflect.FileDescriptor

const file_omnitun_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x17omnitun/v1/tunnel.proto\x12\n" +
	"omnitun.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17omnitun/v1/common.proto\"\x9f\x04\n" +
	"\x06Tunnel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"local_port\x18\a \x01(\x05R\tlocalPort\x12\x1d\n" +
	"\n" +
	"local_host\x18\b \x01(\tR\tlocalHost\x12#\n" +
	"\rcustom_domain\x18\t \x01(\tR\fcustomDomain\x12\x19\n" +
	"\btls_mode\x18\n" +
	" \x01(\tR\atlsMode\x12\x1b\n" +
	"\tauth_mode\x18\v \x01(\tR\bauthMode\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12$\n" +
	"\x0ebytes_in_total\x18\r \x01(\x03R\fbytesInTotal\x12&\n" +
	"\x0fbytes_out_total\x18\x0e \x01(\x03R\rbytesOutTotal\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x83\x02\n" +
	"\x13CreateTunnelRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"local_port\x18\x04 \x01(\x05R\tlocalPort\x12\x1d\n" +
	"\n" +
	"local_host\x18\x05 \x01(\tR\tlocalHost\x12#\n" +
	"\rcustom_domain\x18\x06 \x01(\tR\fcustomDomain\x12\x19\n" +
	"\btls_mode\x18\a \x01(\tR\atlsMode\x12\x1b\n" +
	"\tauth_mode\x18\b \x01(\tR\bauthMode\"B\n" +
	"\x14CreateTunnelResponse\x12*\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x12.omnitun.v1.TunnelR\x06tunnel\"/\n" +
	"\x10GetTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"?\n" +
	"\x11GetTunnelResponse\x12*\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x12.omnitun.v1.TunnelR\x06tunnel\"e\n" +
	"\x12ListTunnelsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\x83\x01\n" +
	"\x13ListTunnelsResponse\x12,\n" +
	"\atunnels\x18\x01 \x03(\v2\x12.omnitun.v1.TunnelR\atunnels\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.omnitun.v1.PaginationResponseR\n" +
	"pagination\"\xc6\x01\n" +
	"\x13UpdateTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tauth_mode\x18\x03 \x01(\tH\x01R\bauthMode\x88\x01\x01\x12,\n" +
	"\x0fmax_connections\x18\x04 \x01(\x05H\x02R\x0emaxConnections\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_auth_modeB\x12\n" +
	"\x10_max_connections\"B\n" +
	"\x14UpdateTunnelResponse\x12*\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x12.omnitun.v1.TunnelR\x06tunnel\"2\n" +
	"\x13DeleteTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"0\n" +
	"\x14DeleteTunnelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x12StartTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"T\n" +
	"\x13StartTunnelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rrelay_address\x18\x02 \x01(\tR\frelayAddress\"0\n" +
	"\x11StopTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\".\n" +
	"\x12StopTunnelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"L\n" +
	"\x15GetTunnelStatsRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"\x9b\x01\n" +
	"\vTunnelStats\x12\x19\n" +
	"\bbytes_in\x18\x01 \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x02 \x01(\x03R\bbytesOut\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x05R\rtotalRequests\"G\n" +
	"\x16GetTunnelStatsResponse\x12-\n" +
	"\x05stats\x18\x01 \x01(\v2\x17.omnitun.v1.TunnelStatsR\x05stats2\x98\x05\n" +
	"\rTunnelService\x12Q\n" +
	"\fCreateTunnel\x12\x1f.omnitun.v1.CreateTunnelRequest\x1a .omnitun.v1.CreateTunnelResponse\x12H\n" +
	"\tGetTunnel\x12\x1c.omnitun.v1.GetTunnelRequest\x1a\x1d.omnitun.v1.GetTunnelResponse\x12N\n" +
	"\vListTunnels\x12\x1e.omnitun.v1.ListTunnelsRequest\x1a\x1f.omnitun.v1.ListTunnelsResponse\x12Q\n" +
	"\fUpdateTunnel\x12\x1f.omnitun.v1.UpdateTunnelRequest\x1a .omnitun.v1.UpdateTunnelResponse\x12Q\n" +
	"\fDeleteTunnel\x12\x1f.omnitun.v1.DeleteTunnelRequest\x1a .omnitun.v1.DeleteTunnelResponse\x12N\n" +
	"\vStartTunnel\x12\x1e.omnitun.v1.StartTunnelRequest\x1a\x1f.omnitun.v1.StartTunnelResponse\x12K\n" +
	"\n" +
	"StopTunnel\x12\x1d.omnitun.v1.StopTunnelRequest\x1a\x1e.omnitun.v1.StopTunnelResponse\x12W\n" +
	"\x0eGetTunnelStats\x12!.omnitun.v1.GetTunnelStatsRequest\x1a\".omnitun.v1.GetTunnelStatsResponseB\x9d\x01\n" +
	"\x0ecom.omnitun.v1B\vTunnelProtoP\x01Z5github.com/omnitun/omnitun/proto/omnitun/v1;omnitunv1\xa2\x02\x03OXX\xaa\x02\n" +
	"Omnitun.V1\xca\x02\n" +
	"Omnitun\\V1\xe2\x02\x16Omnitun\\V1\\GPBMetadata\xea\x02\vOmnitun::V1b\x06proto3"

var (
	file_omnitun_v1_tunnel_proto_rawDescOnce sync.Once
	file_omnitun_v1_tunnel_proto_rawDescData []byte
)

func file_omnitun_v1_tunnel_proto_rawDescGZIP() []byte {
	file_omnitun_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_omnitun_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omnitun_v1_tunnel_proto_rawDesc), len(file_omnitun_v1_tunnel_proto_rawDesc)))
	})
	return file_omnitun_v1_tunnel_proto_rawDescData
}

var file_omnitun_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_omnitun_v1_tunnel_proto_goTypes = []any{
	(*Tunnel)(nil),                 // 0: omnitun.v1.Tunnel
	(*CreateTunnelRequest)(nil),    // 1: omnitun.v1.CreateTunnelRequest
	(*CreateTunnelResponse)(nil),   // 2: omnitun.v1.CreateTunnelResponse
	(*GetTunnelRequest)(nil),       // 3: omnitun.v1.GetTunnelRequest
	(*GetTunnelResponse)(nil),      // 4: omnitun.v1.GetTunnelResponse
	(*ListTunnelsRequest)(nil),     // 5: omnitun.v1.ListTunnelsRequest
	(*ListTunnelsResponse)(nil),    // 6: omnitun.v1.ListTunnelsResponse
	(*UpdateTunnelRequest)(nil),    // 7: omnitun.v1.UpdateTunnelRequest
	(*UpdateTunnelResponse)(nil),   // 8: omnitun.v1.UpdateTunnelResponse
	(*DeleteTunnelRequest)(nil),    // 9: omnitun.v1.DeleteTunnelRequest
	(*DeleteTunnelResponse)(nil),   // 10: omnitun.v1.DeleteTunnelResponse
	(*StartTunnelRequest)(nil),     // 11: omnitun.v1.StartTunnelRequest
	(*StartTunnelResponse)(nil),    // 12: omnitun.v1.StartTunnelResponse
	(*StopTunnelRequest)(nil),      // 13: omnitun.v1.StopTunnelRequest
	(*StopTunnelResponse)(nil),     // 14: omnitun.v1.StopTunnelResponse
	(*GetTunnelStatsRequest)(nil),  // 15: omnitun.v1.GetTunnelStatsRequest
	(*TunnelStats)(nil),            // 16: omnitun.v1.TunnelStats
	(*GetTunnelStatsResponse)(nil), // 17: omnitun.v1.GetTunnelStatsResponse
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
	(*PaginationResponse)(nil),     // 19: omnitun.v1.PaginationResponse
}
var file_omnitun_v1_tunnel_proto_depIdxs = []int32{
	18, // 0: omnitun.v1.Tunnel.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: omnitun.v1.Tunnel.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: omnitun.v1.CreateTunnelResponse.tunnel:type_name -> omnitun.v1.Tunnel
	0,  // 3: omnitun.v1.GetTunnelResponse.tunnel:type_name -> omnitun.v1.Tunnel
	0,  // 4: omnitun.v1.ListTunnelsResponse.tunnels:type_name -> omnitun.v1.Tunnel
	19, // 5: omnitun.v1.ListTunnelsResponse.pagination:type_name -> omnitun.v1.PaginationResponse
	0,  // 6: omnitun.v1.UpdateTunnelResponse.tunnel:type_name -> omnitun.v1.Tunnel
	16, // 7: omnitun.v1.GetTunnelStatsResponse.stats:type_name -> omnitun.v1.TunnelStats
	1,  // 8: omnitun.v1.TunnelService.CreateTunnel:input_type -> omnitun.v1.CreateTunnelRequest
	3,  // 9: omnitun.v1.TunnelService.GetTunnel:input_type -> omnitun.v1.GetTunnelRequest
	5,  // 10: omnitun.v1.TunnelService.ListTunnels:input_type -> omnitun.v1.ListTunnelsRequest
	7,  // 11: omnitun.v1.TunnelService.UpdateTunnel:input_type -> omnitun.v1.UpdateTunnelRequest
	9,  // 12: omnitun.v1.TunnelService.DeleteTunnel:input_type -> omnitun.v1.DeleteTunnelRequest
	11, // 13: omnitun.v1.TunnelService.StartTunnel:input_type -> omnitun.v1.StartTunnelRequest
	13, // 14: omnitun.v1.TunnelService.StopTunnel:input_type -> omnitun.v1.StopTunnelRequest
	15, // 15: omnitun.v1.TunnelService.GetTunnelStats:input_type -> omnitun.v1.GetTunnelStatsRequest
	2,  // 16: omnitun.v1.TunnelService.CreateTunnel:output_type -> omnitun.v1.CreateTunnelResponse
	4,  // 17: omnitun.v1.TunnelService.GetTunnel:output_type -> omnitun.v1.GetTunnelResponse
	6,  // 18: omnitun.v1.TunnelService.ListTunnels:output_type -> omnitun.v1.ListTunnelsResponse
	8,  // 19: omnitun.v1.TunnelService.UpdateTunnel:output_type -> omnitun.v1.UpdateTunnelResponse
	10, // 20: omnitun.v1.TunnelService.DeleteTunnel:output_type -> omnitun.v1.DeleteTunnelResponse
	12, // 21: omnitun.v1.TunnelService.StartTunnel:output_type -> omnitun.v1.StartTunnelResponse
	14, // 22: omnitun.v1.TunnelService.StopTunnel:output_type -> omnitun.v1.StopTunnelResponse
	17, // 23: omnitun.v1.TunnelService.GetTunnelStats:output_type -> omnitun.v1.GetTunnelStatsResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_omnitun_v1_tunnel_proto_init() }
func file_omnitun_v1_tunnel_proto_init() {
	if File_omnitun_v1_tunnel_proto != nil {
		return
	}
	file_omnitun_v1_common_proto_init()
	file_omnitun_v1_tunnel_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omnitun_v1_tunnel_proto_rawDesc), len(file_omnitun_v1_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_omnitun_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_omnitun_v1_tunnel_proto_depIdxs,
		MessageInfos:      file_omnitun_v1_tunnel_proto_msgTypes,
	}.Build()
	File_omnitun_v1_tunnel_proto = out.File
	file_omnitun_v1_tunnel_proto_goTypes = nil
	file_omnitun_v1_tunnel_proto_depIdxs = nil
}
