global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: 'omnitun-server'
    static_configs:
      - targets: ['omnitun-server:9090']
        labels:
          component: 'api'
  - job_name: 'omnitun-relay'
    static_configs:
      - targets: ['omnitun-relay:9090']
        labels:
          component: 'relay'
