apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omnitun.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omnitun.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  postgres-user: {{ .Values.postgresql.auth.username | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  postgres-db: {{ .Values.postgresql.auth.database | quote }}
  database-url: {{ printf "postgres://%s:%s@%s:5432/%s?sslmode=disable" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "omnitun.postgresql.fullname" .) .Values.postgresql.auth.database | quote }}
