apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnitun.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omnitun.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "omnitun.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
